### PR TITLE
Idempotency: yum_install_or_update

### PR DESCRIPTION
**Pull request by gderosa**
With this change, you can run the script multiple times, smoothly, even under `bash -e` if you like...

Can be useful in deployment scripts etc.

(or let me know is there's a simpler way?)

Thanks!

### CODE REVIEW

**Comment by b-harper** [comment]
Hey @gderosa,

Thanks for taking the time to submit this pull request.  I am curious on your work flow and how this change comes into play.

The thought behind the script is to just to install the epel-release and ius-release packages.  Once those packages are installed, they can be updated like any other package as both EPEL and IUS provide the release packages in their repositories.

**Comment by gderosa** [comment]
The concrete use case right now is an internal/closed web application, or precisely its automated deployment and I can't provide more details.

However, I thought this can be useful to a general audience, but if that's not the case, you can ignore this PR.

The general idea is being able to run this script, or actually a sequence of scripts including this one, all the times there is a change on the software depending on these repos. You can run this the first time, and all the other following times, again and again. It'll be an install the first time, and a no-op or update in the following times, without errors.

But you still might want to run `bash -e` because you want all other errors to block the deployment e.g. if there's a failing test. (you don't want to roll in production anything broken)

This can work well with Jenkins (e.g. called from within a build script) or possibly invoked by Chef, Puppet, Ansible and similar tools.

I hope this answers your question :)

Again, up to you to decide whether this is too much of a specific use or not.

Thanks anyway.

**Comment by b-harper** [comment]
Hey @gderosa,

Thanks for the additional information.  The third paragraph was the type of information I was looking for.  When this script was created, we did not consider the use case of the script getting run more than once.  Adapting the script to be run multiple times and return errors correctly seems like a good idea.

In regards to configuration management software like Chef, Puppet and the rest, I would not recommend this script.  Those tools were developed to move past simple scripting.  See our [automation-examples][0], for some example.  [Chef][1] and [Puppet][2] have some examples of their own.

-Ben
[0]: https://github.com/iuscommunity/automation-examples
[1]: https://supermarket.chef.io/cookbooks/yum-ius
[2]: https://forge.puppet.com/kemra102/ius

**Comment by carlwgeorge** [comment]
Both EPEL and IUS ship our release RPMs in the repo, so using the script to ensure the release packages are up to date has little value.  As far as idempotence, that can be achieved just by adding `|| :` to the end of the yum commands, rather than adding a new function.  For example:
```sh
        7*) yum -y install https://centos7.iuscommunity.org/ius-release.rpm || : ;;
```
If you update your pull request to use that approach we'll merge it in.

**Comment by gderosa** [comment]
@carlwgeorge, the problem with the approach you suggest is that any error in yum install will be ignored and the script will pretend to succeed even if there are e.g. serious dependency conflicts on the system, or a network failure or whatever else...

With my approach, the second attempt to yum update will tell us the truth  whether the problem was just the package already installed or something else...

 I understand now my local customisation was just perhaps too specific to my use case (where it's doing its job great) so I'm keen to close this PR, and I don't have much time to discuss this further (it was supposed to be a simple get-it-if-you-like 😊).

But feel free to use any of the ideas discussed here for your own modifications if/when you wish.

Thanks.

**Pull request closed without merging**
